### ISSUE TITLE
Entry text is spanning multiple lines

### ISSUE THREAD

**Issue by shivamkalra** [tmalsburg/helm-bibtex#106]
Even though entry text can be fit into single line but they are spanning multiple lines.

![2016-04-10-195012_1919x140_scrot](https://cloud.githubusercontent.com/assets/1386352/14413891/92906a68-ff55-11e5-9123-69d9a8ea76fa.png)

**Comment by tmalsburg** [comment]
Oh, I thought I had already fixed that.  I think the problem is that your fringes are wider than usual.  Unfortunately, it is terribly difficult to make stuff pixel precise in Emacs.  Could you please tell me what output you get the the following two function calls? 

``` elisp
(frame-parameter nil 'left-fringe)
(frame-parameter nil 'right-fringe)
```

**Comment by shivamkalra** [comment]
@tmalsburg Here is the output. I believe that `right-fringe` is off by 1 pixel that might be causing this issue?
```
> (frame-parameter nil 'left-fringe)
10 (#o12, #xa, ?\C-j)

> (frame-parameter nil 'right-fringe)
11 (#o13, #xb, ?\C-k)
```

**Comment by tmalsburg** [comment]
Frankly, I don't know what's going on.  Since it's working on my machine, I can't debug this.  You may want to have a look at the function `helm-bibtex-window-width` which already takes fringes into account.  Perhaps you can play with this function and see if you can figure out how the calculations have to be changed in order to make it work in your setup.  Otherwise, the easiest ad-hoc solution might be to reduce the size of your fringe.

**Comment by shivamkalra** [comment]
@tmalsburg Thanks for the suggestion. I end up in just forcing `1-` to `window-body-width`. I'm not sure why `window-body-width` is off by 1 for me.

**Comment by tmalsburg** [comment]
Oh, looking at your screenshot again, I think I know what's causing the problem.  Your PDF symbol is wider than the other characters.  So the font isn't really fixed-width but the calculations assume it is.  You could replace the PDF symbol by something else using the variable `helm-bibtex-pdf-symbol`.
