### ISSUE TITLE
Opening PDF files

### ISSUE THREAD

**Issue by higham** [tmalsburg/helm-bibtex#169]
At some point in the last few weeks, after updating from Melpa, I lost the ability to open PDF files from Helm-BibTeX (e.g., Action F1), even though the relevant settings in my .emacs have not changed.  I've fiddled around with the customization options to no avail, and I'm sure the paths to the PDFs are correctly set.  F1 still opens DOIs OK.

**Comment by tmalsburg** [comment]
Hm, it's working fine on my system and I didn't make any changes in helm-bibtex since mid-December.  The last changes I made were not related to opening PDFs.  I suspect that the cause for this issue is not in helm-bibtex.  Do you get an error message?  Perhaps a problem with your PDF viewer?  Which viewer are you using and on what operating system?

**Comment by higham** [comment]
It happens on both Windows (7 and 10) (Sumatra) and Mac (Skim).
No error message with F1, but using the

(defun bibtex-completion-open-pdf-of-entry-at-point ()
  (interactive)
  (save-excursion
    (bibtex-beginning-of-entry)
    (when (looking-at bibtex-entry-maybe-empty-head)
      (bibtex-completion-open-pdf (bibtex-key-in-head)))))

function with point in a bib entry (from the earlier thread
https://github.com/tmalsburg/helm-bibtex/issues/121#issuecomment-237981605
) on both Windows and Mac the minibufferr error message is "No PDF(s) found."

Also,

(defun bibtex-completion-njh-edit-note ()
  (interactive)
  (save-excursion
    (bibtex-beginning-of-entry)
    (when (looking-at bibtex-entry-maybe-empty-head)
      (bibtex-completion-edit-notes (bibtex-key-in-head)))))

which again used to work, now says 

progn: Wrong type argument: listp, "alhi09"

the latter being the key of the entry the point is in.
This is Emacs "25.1.1"
And this variable is set as it always was:

bibtex-completion-library-path is a variable defined in ‘helm-bibtex.el’.
Its value is ("~/pdf_papers" "~/pdf_papers/higham" "~/pdf_books")

**Comment by higham** [comment]
Correction: the error message is
progn: Symbol’s function definition is void: bibtex-completion-open-pdf
even though I have (for Windows, and similiarlt for Mac)
(setq bibtex-completion-pdf-open-function       ;; Open PDF in Sumatra
    (lambda (fpath) (shell-command
             (concat "start /pgm SumatraPDF.exe -reuse-instance " fpath )))))

**Comment by tmalsburg** [comment]
If `bibtex-completion-open-pdf` is undefined that means that something is seriously amiss with your helm-bibtex setup. I'm surprised that helm-bibtex is working at all.  I would try to debug this with `emacs -q`, a minimal helm-bibtex configuration, and then adding your customizations step by step.

**Comment by jagrg** [comment]
I can open pdfs from helm-bibtex without a problem, so I'm not sure why that fails for you. Regarding `bibtex-completion-open-pdf-of-entry-at-point` and `bibtex-completion-njh-edit-note`, I think you need to wrap `bibtex-key-in-head` with the `list` function, otherwise the bibtex-completion functions fail. For example: `(bibtex-completion-open-pdf (list (bibtex-key-in-head)))`.

I remember having to fix a few of these in org-ref a while back. I'm not sure when this changed, but I'm pretty sure that these bitex-completion functions used to accept strings in the past.

**Comment by tmalsburg** [comment]
>  but I'm pretty sure that these bitex-completion functions used to accept strings in the past.

My somewhat vague memory is that we changed this to accommodate ivy-bibtex.  But these changes happened quite a while ago, so I'm not sure whether that is the explanation for the present issue.

**Comment by higham** [comment]
Thanks.   I'm on the way to having everything working again, and jagrg's
tip has certainly helped.

**Comment by tmalsburg** [comment]
I think this can be closed, right?
