### ISSUE TITLE
searching with particular fields

### ISSUE THREAD

**Issue by DrWaleedAYousef** [tmalsburg/helm-bibtex#181]
how can I search for articles with author A and volume B. should I say something like:

author A volume B

**Comment by tmalsburg** [comment]
There is currently no way to search for values in specific fields.  Just enter the author and volume number but this will also match entries which have this number in another field.

**Comment by tmalsburg** [comment]
Note that you have to add volume to `bibtex-completion-additional-search-fields` to be able to search for it.

**Comment by jdtonkin** [comment]
Hi Titus. Just wondering if there's any plans in the works for incorporating this functionality? Thanks!

**Comment by tmalsburg** [comment]
It's not trivial because we're currently relying on Helm to do the matching and Helm doesn't support that (to my knowledge).  Someone would have to write a matching engine for Helm (and Ivy) and that someone is unfortunately not going to be me.  This would be a great feature but I simply don't have the time.  If someone else wants to work on it, I'd be happy to provide guidance.
