### ISSUE TITLE
Feature request: IEEE searches

### ISSUE THREAD

**Issue by notuntoward** [tmalsburg/helm-bibtex#190]
The IEEE journals

http://ieeexplore.ieee.org/Xplore/home.jsp

are widely used, and in addition, the bibtex the search engine returns is often of better quality than, for example Google Scholar -- better handling of umlauts, full journal details, etc.  IEEE will also retrieve the paper abstract, which I find valuable.

So a feature request: please add IEEE as a search option.

**Comment by tmalsburg** [comment]
Bibtex from Google Scholar is completely useless. However, we already have support for Crossref and in my experience it delivers excellent Bibtex.  I'm not familiar with IEEE. (Could you please provide a link?)  What would we gain by adding IEEE?

**Comment by notuntoward** [comment]
Crossref is OK, but it doesn't handle things like umlauts.  Try searching, for example:

Vertical digital beamforming versus multipath height finding

and look at Jürgen.  In this case, the advantage of the IEEE bibtex is not visible because the authors' first names are abbreviated, but this does make a difference elsewhere.  The other big advantage is that IEEE will give you the  paper abstract; I and others put these in our bibtex files, where they are useful for searching for "that paper about this that I know I read sometime."  This is the reason why Jabref includes the IEEE abstract download option.

The homepage for IEEE is:  http://ieeexplore.ieee.org/Xplore/home.jsp

And IEEE is one of the most important places to go for papers on electronics, software engineering and machine learning -- key topics for a lot of people nerdy enough to use emacs!

**Comment by tmalsburg** [comment]
I just checked, Umlauts work for all publications that I tried.  I think the problem with your article may not be Crossref but the source from which Crossref retrieved the information, not sure though.

I'm happy to include support for IEEE if that is useful for some people but I personally won't work on it because IEEE is for engineering and not relevant in my research area.  I also think that it would be better to add IEEE support to [biblio.el](https://github.com/cpitclaudel/biblio.el) and then it would also be available in helm-bibtex (we get Crossref support through biblio.el).  biblio.el probably also has some infrastructure that makes it easier to write something for IEEE.

**Comment by notuntoward** [comment]
OK, i'll make a biblio.el request.  Thanks.

**Comment by tmalsburg** [comment]
Great, good luck!

**Comment by tmalsburg** [comment]
I'm closing this for now. Feel free to reopen once there is IEEE support in biblio.el.  Then we can make the necessary adjustments in helm-bibtex.

**Comment by senselessDev** [comment]
Just for reference: [biblio.el supports IEEE now](https://github.com/cpitclaudel/biblio.el/issues/16)

**Comment by tmalsburg** [comment]
Yes, we had already added it a couple of days ago in 4655e1d89ff8df980b68ac85d999efb85dbae3cf.
