### ISSUE TITLE
pass candidates to actions more efficiently?

### ISSUE THREAD

**Issue by ericdanan** [tmalsburg/helm-bibtex#208]
I am a bit puzzled by one thing. The candidates that `helm-bibtex` receive from `bibtex-completion-candidates` are conses where the `car` is the search string and the `cdr` is the entry as an alist. Then when the filtered candidates are transformet by `helm-bibtex-candidates-formatter`, the `car` is transformed to look nice, but the `cdr` is also reduced to the entry key. And then, many (6) action functions start by retrieving the discarded information through `bibtex-completion-get-entry`, which involves copying all bibliography files to a temp buffer to locate and process the entry (possibly twice if there is a crossref).

Wouldn't it be more efficient to keep the whole entry in the `cdr` and pass this to the action functions instead of the mere key, avoiding the need to resort to `bibtex-completion-get-entry`? Or is it that the entry alist returned by `bibtex-completion-get-entry` is potentially different and more relevant than that from `bibtex-completion-candidates`? (I can't see why though)

Note that `ivy-bibtex` only transforms the display string, so it does pass the whole alist, but this list is then reduced to the key by `ivy-bibtex-ivify-action`.

**Comment by tmalsburg** [comment]
Yes, this part is a bit messy. I think I didn't keep the whole entries because this consumed too much memory with larger bibliographies (e.g. crypto.bib).  But to be honest, I'm not sure.

> Or is it that the entry alist returned by bibtex-completion-get-entry is potentially different and more relevant than that from bibtex-completion-candidates? (I can't see why though)

There is raw entries and beautified entries (braces and quotes removed), also there is original entries and entries with fields from crossreferenced entries merged, further there are stripped-down entries that contain only information needed for display (e.g. in the cache).   So there is a good chance that `bibtex-completion-get-entry` returns something else than what we would get through the candidate list.  Would have to check.

More generally, though, I'm pretty sure that things can be simplified in some way. The code grew organically and certainly isn't as clean as it could be were everything planned from the start.

**Comment by ericdanan** [comment]
> there are stripped-down entries that contain only information needed for display (e.g. in the cache).

Yes, all the actions resorting to `bibtex-completion-get-entry` actually need fields that are not stored in the cache (at least with the default value of `bibtex-completion-additional-search-fields`). And if storing one more field in the cache is costly for large bibliographies, it is better not to store them there and grab them afterwards for the selected candidates only.

Thanks.
