### ISSUE TITLE
Automatic Reparsing of Bibfile

### ISSUE THREAD

**Issue by gelbwald** [tmalsburg/helm-bibtex#242]
Since on-demand parsing the library when calling e.g. helm-bibtex can take a few seconds, it would be better for the workflow if the library could be watched for changes and then reparsed automatically (or perhaps reparse only the changed entries).

**Comment by tmalsburg** [comment]
The library is actually being watched for changes and reread only when necessary.  Reparsing only the changed entries doesn't really help because checking each entry would probably take longer than just rereading everything.

How long does it take to read your library and how many entries do you have?

**Comment by tmalsburg** [comment]
Oh, sorry, after rereading, I get what you mean: you're proposing that the library is continually being watched.  That's actually a great idea and probably not too difficult to implement.  I don't have the time to work on this currently but if you want to give it a shot, I'd be happy to give you input and feedback on an PR.

**Comment by tmalsburg** [comment]
I have a solution using inotify (via `inotify-add-watch`). Works beautifully but only on Linux.   For reasons that I don't understand yet `file-notify-add-watch` (described in the link above) is not part of my current development Emacs.

**Comment by tmalsburg** [comment]
Pushed a new version: https://github.com/tmalsburg/helm-bibtex/commit/01a37a593436ca7fc361490093ab084a626fc425

Please test and let me know whether it works as expected.

One problem that might arise is that Emacs blocks when the bibliography is reloaded.  Some users might find that annoying, especially when loading is slow (2s on my system because I'm not using the file field for PDFs but the naming scheme `bibtex_key.pdf`).

**Comment by tmalsburg** [comment]
Just tried reloading with threads but it's still blocking.  Hm ...

**Comment by bdarcus** [comment]
Seems like this could be closed, as this was merged; right?

But while I'm here, is there any reason not to extend this for PDFs and notes? As in, if I add a PDF for note to my respective configured directories, bibtex-completion will update the candidates. If not, I can open a new issue.

**Comment by tmalsburg** [comment]
> But while I'm here, is there any reason not to extend this for PDFs and notes? 

Good idea. Please feel free to create a new issue.  The only downside that I see is that it could cause more reloads than users might like, especially users with very large bibliographies.  For instance, say you have all notes in one file and you edit this file frequently and accordingly save it frequently, then Emacs would block every time you save that file and with large bibs like crypto.bib it would block for (I think) more than 30s.  This could be addressed by allowing users to configure autoreloading on a fine-grained level but this would be complicated, potentially error prone, and perhaps not worth it.  Not sure.
