### ISSUE TITLE
optional caching

### ISSUE THREAD

**Issue by malb** [tmalsburg/helm-bibtex#26]
It would be great to use helm-bibtex on http://cryptobib.di.ens.fr/ but the .bib file is 10MB meaning it takes a moment to parse it.

Hence, it would be great if parsing results could be cached.

**Comment by tmalsburg** [comment]
I agree, this would be a useful addition.  I'll look into it when I have time. Shouldn't be too hard to implement.  Pull requests are welcome, too.

**Comment by tmalsburg** [comment]
I created a branch called  `cache-bibliography`.  In my setup it works beautifully: after the intial parse of crypto.bib, subsequent helm-bibtex session open instantly.  Caching is not optional because I don't see a reason for not using it.  A cached parse of the bibliography can also make some other operation much faster (but this is not yet implemented in the branch).

Could you please test it and let me know if it works for you as well?  Thank you.

**Comment by malb** [comment]
I played with it for a bit and it seems to be working fine. Thank you!

**Comment by tmalsburg** [comment]
Thanks for testing.  I'll make some more changes to take full advantage of the cached data and then merge to master.
