### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by kirk86** [tmalsburg/helm-bibtex#262]
Hi and thank you for providing helm-bibtex. 
I was wondering if it possible to add some additional functionality.
1. Ability to add a bibtex entry in the .bib file by pointing to a pdf file, after the entry has been extracted and entered in the .bib file the pdf should be renamed according to user defined naming convention in the folders indicating during the initial setup of the helm-bibtex
2. Sorting of the bibtex entries in the minibuffer after executing `helm-bibtex`

**Comment by tmalsburg** [comment]
1. What do you mean by "after the entry has been extracted"?  Extracted from where?

2. Some users might appreciate sorting, but it's not a feature that I personally need, so I'm likely not going to work on it.  If you'd like to make PR, I'd be happy to give your input.

**Comment by kirk86** [comment]
@tmalsburg thank you for the comments.

>     1. "after the entry has been extracted"?  Extracted from where?

that could be from a third emacs library which given an isbn, doi, arxiv id can insert the bib entry in your bibliography file, or you could be adding it manually.

>     2. If you'd like to make PR, I'd be happy to give your input.

Thank you!

Closing it to keep things simple.

**Comment by tmalsburg** [comment]
Oh, I see.  If there is a package that can give you bibtex for a PDF of an article, I'd love to add this feature.

**Comment by tmalsburg** [comment]
I agree that this is a desirable feature but what do we gain by duplicating it in helm-bitbex when it already exists in org-ref?  Can we just import the relevant bits and pieces from there?

**Comment by kirk86** [comment]
> duplicating it in helm-bitbex

I agree that duplicating is not the solution, but I dunno if there exists the potential of a merge where org-ref gets an upgrade as well and becomes more robust.

> Can we just import the relevant bits and pieces from there?

I think that is possible, thankfully org-ref is not a huge project and most of the functionality is already separated into different files such as `org-ref-arxiv.el, org-ref-pubmed.el, org-ref-scopus.el, org-ref-utils.el` etc.

**Comment by jkitchin** [comment]
There is an outline for dragging a pdf/url onto emacs and extracting this information in org-ref, but this is very difficult in general. There is in my experience not many pdf/urls with standard metadata to read (or this would be easy). Instead you have to scrape them via pdftotext and regular expressions to try to get a doi out. Many dois are easy to get, but there a some that defy regular expressions (e.g. https://dx.doi.org/10.1016/0022-3697(92)90168-D has () in it, and check out https://doi.org/10.1002/(SICI)1521-4125(200004)23:4%3C324::AID-CEAT324%3E3.0.CO;2-K), and are otherwise hard to get. There are 10 different patterns in org-ref that are used now. I also find drag and drop in emacs to be very platform dependent, and sensitive to how emacs was built in some cases, so it does not work reliably across Mac/Windows/Linux. I haven't found this feature as useful as the first one, and don't use it for anything. It is much more reliable to just copy the doi and paste it into a command in emacs to download a bibtex entry.

In contrast, given a doi for an article, you can easily retrieve a bibtex entry and sometimes download the pdf too. There are functions for getting bibtex entries from pubmed, and arxiv. For cases where you don't have a doi handy, org-ref provides a search interface to crossref which also can download bibtex entries. So if you have a doi from your paper, I would use that to get the bibtex entry. org-ref will save the key on the clipboard, so then in your pdf, just click "Save as", navigate to where you want it, and paste the key in the filename. It is hard to get more streamlined than that (if you have an idea, let me know!). Sometimes the metadata is not available, or badly formatted for this, and not every entry type is supported, but there aren't issues on any major deficiencies that I know of.

The way automatically downloading a pdf works in general is that there has to be a way to compute a url to the pdf from an identifier. For arxiv it is pretty easy. For a doi, it is not easy because you have to first try to follow the https://doi.org/doi link, which gets redirected to a publisher site, then from the publisher site compute the url to a pdf. The difficulty is that each publisher does this differently, leading to a collection of recipes for each publisher. Some publishers make it very difficult to do this (on purpose), and sometimes it is not even possible, or the publishers change their tactics to avoid automatic downloads. Finally, access to the pdf all depends on whether you are allowed to access them, and this is usually controlled by your ip address. org-ref has a collection of these recipes, and occasionally someone adds to them, or alerts me that they no longer work and they get fixed.  This feature is the one that I think makes me more productive.

Regarding sorting, you may find some inspiration in org-ref-helm-cite, which has support for sorting by year, 1st author or key in an alternative helm interface.

**Comment by kirk86** [comment]
@jkitchin thank you so much for the detailed answer.
Regarding extracting metadata from a bulk of pdfs or a directory this is how zotero does it:
```
How Retrieve Metadata Works

In trying to retrieve metadata for PDFs, Zotero first reads the text content of the PDF and then runs through three steps:

    It searches for a DOI in the first 80 lines of text and queries the CrossRef database for metadata
    It searches for an ISBN in the first 80 lines of text and queries Open WorldCat for metadata
    It picks out a line from the middle of the document and queries google scholar for the verbatim line (the search contains the line in quotation marks) and retrieves the metadata. It will try this up to three times per document.

These steps are designed to minimize false positives, so that Zotero should only in the rarest of cases (less than one percent of cases) find the wrong metadata for a PDF. It will fail more frequently depending on the types or PDFs used: For more recent journal articles, failure rates should generally be below ten percent, but for older articles or gray literature they can be much higher.

In addition, Google Scholar, aiming to prevent “bots” from scraping its database, will lock you out after a certain amount of rapid, automatic queries (typically around 50). In those cases Zotero will advise you that you have reached your query limit. You can then either move your computer to a different internet connection (IP-address), or wait for about a day to resume retrieving metadata. You will still be able to use Google Scholar regularly by filling out a Captcha.
```
It could be nice if `org-ref-pdf-dir-to-bibtex` has some of that functionality it would make the approach more robust to "noise".

About sorting, I can't find any function `org-ref-helm-cite` in `M-x`.

Finally, I have question about `org-ref-clean-bibtex-entry`, is there any possibility to define the formatting structure, e.g. the number of spaces between words and how fields in a bibtex entry should be ordered?

Here's a comparison between jabref:
```
@article{engelbart68:mother_of_all_demos,                                                                                                   
  author       = {Douglas C. Engelbart AND William K. English},                                                                                                    
  title        = {{A Research Center for Augmenting Human Intellect}},                                                                                                   
  year         = 1968,                                                                                                      
  archiveprefix= {Conf. Proc. of AFIPS},                                                                                                  
}
```
and what `org-ref-clean-bibtex-entry` does:
```
@article{baehrens_how_to_explain_indiv_decis,                                                                                                   
  author =       {Baehrens, David and Schroeter, Timon and Harmeling,                                                                                                     
                  Stefan and Kawanabe, Motoaki and Hansen, Katja},                                                                                                     
  title =        {How To Explain Individual Classiﬁcation Decisions},                                                                                                 
  pages =        {29},
  abstractNote = {After building a classiﬁer with modern tools of                                                                                              
                  method.},                                                                                  
}
```
As you can see the number of spaces between `=` is not equal and maybe you would like to change the order of the fields so that you can keep things consistent. Is that possible?

**Comment by jagrg** [comment]
> As you can see the number of spaces between `=` is not equal [...]

Try setting bibtex-align-at-equal-sign to t.
