### ISSUE TITLE
Handling of special characters

### ISSUE THREAD

**Issue by dschrempf** [tmalsburg/helm-bibtex#293]
I would like to find bibliography entries without the need to type special characters in the search field. For example, I would like to find paper of the author Müller by typing `muller` (especially when the bibtex entry is not containing `muller`, for example, when Müller is not the first author). Do you think this is easy to implement?

In detail, as an example, the letter `u` should not only search for `u`, but also for `üűú`, and so on and so forth.

Thank you,
Dominik

**Comment by tmalsburg** [comment]
Helm-bibtex (and ivy-bibtex I presume) support regular expressions.  So I would simply search for `m.ller` where the `.` matches any character.  Probably good enough for most use cases.  If you want something that systematically translates characters, I would check the help documentation.  I would not be surprised if they had infrastructure that allows you to include custom filters for search terms.  Hope that helps.

**Comment by dschrempf** [comment]
The solution with regular expressions certainly helps, but I still think that a map from, e.g., `a` to all special characters built on `a`, is what we actually want. This is standard in many search engines (like Google) anyways. I understand though, if you nor anybody else have enough time to implement this feature.

**Comment by tmalsburg** [comment]
Typo in my previous response. I meant "check the helm documentation" (not "help").

> Edit: Actually, this may mean that the feature can be implemented really easily. One just has to replace each vowel with the corresponding regex. But of course, there are more cases such as n and ñ and so on.

The code is simple, but two problems: 1. There are probably endlessly many cases that we'd have to handle and I don't know what they are.  (Is there an ISO standard for this?)  And 2., the resulting regular expressions will likely become so complex that they slow down the search.  Though, I have no strong intuition how much (because of 1.).  I don't want to rule out that we implement some version of this but my suspicion is that this is one of those features that look trivial at first and then turn out to be horrifically complex if you want to do it properly.

**Comment by jagrg** [comment]
This is called character folding (see [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Lax-Search.html#Lax-Search)), and it works with isearch and swiper when search-default-mode is set to #'char-fold-to-regexp.

**Comment by tmalsburg** [comment]
Thanks, @jagrg!  I think this means that this feature should be implemented at the helm level for the benefit of all helm sources not in helm-bibtex specifically.
