### ISSUE TITLE
Relative paths in links

### ISSUE THREAD

**Issue by mgttlinger** [tmalsburg/helm-bibtex#303]
I have a BibTeX file I collaboratively edit with coauthors and we keep the relevant pdf files in the same folder structure.

Inserting file links in a collaboratively used org file inserts absolute file paths which I currently have to manually edit so that they work for everyone.

Is there an option to insert relative paths or would you accept a PR implementing this functionality (as an alternative)?

**Comment by tmalsburg** [comment]
Just to be sure I understand what you want.  We have `bibtex-completion-format-citation-org-link-to-PDF` that inserts org links to PDFs with absolute paths.  You'd like to have a version that does the same but with paths relative to the location of the org file?  If yes, I don't think we have this capability but it would of course be easy to create a version of `bibtex-completion-format-citation-org-link-to-PDF` that achieves this.  Not sure though whether I would include it in helm-bibtex as the use case you're describing sounds very niche.  I recommend writing this function and including it in org file that you're jointly editing so that it is automatically loaded when the file is opened.  This way every contributor to this file is using the same citation function.  Would that work?

**Comment by mgttlinger** [comment]
Yeah that would also work.
