### ISSUE TITLE
Discrepancy in Emacs version dependencies

### ISSUE THREAD

**Issue by jethrokuan** [tmalsburg/helm-bibtex#325]
https://github.com/tmalsburg/helm-bibtex/blob/16b113692966da9bbe1f9f0ed8dcbfd2db61a7ba/helm-bibtex.el#L7

It looks like `bibtex-completion` requires `26.1`, while `helm-bibtex` requires `24.1` and ` bibtex-completion`. I think it would be best to standardize on a version (26.1 maybe).

Note that the changes in packaging also broke `org-ref`'s CI:

https://travis-ci.org/github/jkitchin/org-ref/jobs/682872054#L1123

which runs tests on Emacs 25.1 and 25.3.

**Comment by tmalsburg** [comment]
> It looks like bibtex-completion requires 26.1, while helm-bibtex requires 24.1 and bibtex-completion. I think it would be best to standardize on a version (26.1 maybe).

Not sure I understand why? Isn't it best for every package to indicate just it's own requirements instead of those of it's dependencies?  Package.el et al. should handle the rest automatically, no? You might say, that the helm-bibtex requirements might create incorrect expectations but what if we specify 26.1 as in bibtex-completion and then dash.el requires 26.2? We'd still create wrong expectations.

> Note that the changes in packaging also broke org-ref's CI:

Is there something I can do about this?  I guess @jkitchin needs to take care of this.  Alternatively, if Emacs 26.1 is considered too recent, I could try to make do with earlier versions of Emacs.  (I didn't get any complaints yet and assumed that most people are on Emacs >= 26.1.)

**Comment by jethrokuan** [comment]
> Isn't it best for every package to indicate just it's own requirements instead of those of it's dependencies? 

Right, I'd forgotten that `ivy-bibtex`, `helm-bibtex`, and `bibtex-completion` were shipped as separate packages. That makes sense.

> Is there something I can do about this? 

No, just raising it here. If it happens that `bibtex-completion` doesn't need features in Emacs 25 and 26, and can work with Emacs 24.1, then dropping the 26.1 dep would resolve that, but of course it's also okay to keep it at 26.1.

**Comment by tmalsburg** [comment]
> Right, I'd forgotten that ivy-bibtex, helm-bibtex, and bibtex-completion were shipped as separate packages. That makes sense.

Ah, I see.

> No, just raising it here. If it happens that bibtex-completion doesn't need features in Emacs 25 and 26, and can work with Emacs 24.1, then dropping the 26.1 dep would resolve that, but of course it's also okay to keep it at 26.1.

Are there any stats available on what Emacs versions people are using?  I guess (M)ELPA must in principle have access to that info.  I'd be happy to make my stuff more compatible with older versions if that is not a complete waste of time because everyone is using recent emacs anyway.
