### ISSUE TITLE
Syntax error (check esp. commas, braces, and quotes)

### ISSUE THREAD

**Issue by AtomicNess123** [tmalsburg/helm-bibtex#351]
I can't seem to pinpoint the exact error when I get this message. The bibtex entries seem fine in their syntax.
How to fix this issue? Thanks.

**Comment by tmalsburg** [comment]
This error message is generated by bibtex.el which is a different package than the one maintained in this repository.  The message almost certainly arises because there's a syntax error in your BibTeX file. These can be difficult to see, so you'll have to do some work to pin it down, e.g. separate the file in two halves and then check in which half you get the error and then repeat.  If you have biber installed, you can also use `biber --tool -V bibliography.bib`.

**Comment by AtomicNess123** [comment]
Could you give me the link to the biber tool?
