### ISSUE TITLE
Customize ivy-bibtex to go to a specific online database automatically as a fallback option

### ISSUE THREAD

**Issue by DiogoFerrari** [tmalsburg/helm-bibtex#391]
Is there a way to go to Google Scholar automatically if there is no match in my .bib file using ivy-bibtex?

The current procedure needs a few steps: M-o f, and then select Google Scholar. I would like to jump automatically to google scholar if I press <RET> on ivy-bibtex and there is no match in my .bib file.

helm-bibtex doest that, but I could not figure out a way to do that using ivy-bibtex.

**Comment by tmalsburg** [comment]
I think that's a limitation of ivy-bibtex' UI and not something that we can easily fix here.  But I'm not an expert for ivy and may be wrong.

I personally prefer helm because it's more powerful.  In the early days of ivy, people said they liked it because it was lightweight, but it's basically doomed to reinvent helm because helm's features *are* useful.

I'm going to close this issue but feel free to reopen when you figure out a way to address this.
