### ISSUE TITLE
Feature request: Open the associated file more powerfully

### ISSUE THREAD

**Issue by HEMCSEC** [tmalsburg/helm-bibtex#47]
It would be better to search the associated file  having the string "bibtex-key" in its name, instead of just whose name is "bibtex-key.pdf", thanks.

**Comment by tmalsburg** [comment]
The thing is, people have entries like the following:

- NameEtAl2014
- NameEtAl2014XYZ

where the first is a journal article and the second a presentation at XYZ conference.  If we search for files with NameEtAl2014 in their name, both items match. See #40 for a related problem.

**Comment by HEMCSEC** [comment]
Thanks for your reply. You're right, it is indeed a problem. Then how about provide a option and let the user himself to decide how to define the search string for the associated file with regular expression?

**Comment by tmalsburg** [comment]
> let the user himself to decide how to define the search string

It possible but it smells of feature creep.  I don't see what we would gain.

**Comment by svaiter** [comment]
Hi.
I want to add a small comment on this feature request. For instance, in my case, I have the following naming scheme:
bibtex-key0.pdf, bibtex-key1.pdf, etc. in order to support for instance supplementary materials. About 95% of my references have only one file associated. For the moment, I simply redefined `helm-bibtex-find-pdf` as
```elisp
(defun helm-bibtex-find-pdf (key)
  "Searches in all directories in `helm-bibtex-library-path' for
a PDF whose name is KEY + \".pdf\".  Returns the first matching PDF."
  (car (-filter 'f-exists?
                (--map (f-join it (s-concat key "0.pdf"))
                       (-flatten (list helm-bibtex-library-path))))))
```
which is not very clean.
Maybe you can make a quick note in the README to state that the naming convention used by helm-bibtex is bibtex-key.pdf, but one can hack `helm-bibtex-find-pdf` in order to have a finer control ?

**Comment by tmalsburg** [comment]
Yes, now that we have `helm-bibtex-find-pdf' it's much easier to accommodate special preferences and I will add a note about that.  However, why don't you use a naming scheme where the main article is BibTeXkey.pdf and the supplemental PDFs BibTeXkey1.pdf and so forth.  This way you don't need to tweak the code.

Thanks for the suggestion.

**Comment by tmalsburg** [comment]
BTW, I just noticed that the `(car (-filter ...` can be simplified to `(-first ...`.

**Comment by tmalsburg** [comment]
Ok, [done](https://github.com/tmalsburg/helm-bibtex#different-naming-schemes-for-pdf-files).  I think it's now sufficiently easy for users to change the naming scheme and we can close this issue.  Thanks everyone.
