### ISSUE TITLE
Request for multiple directories in helm-bibtex-library-path

### ISSUE THREAD

**Issue by higham** [tmalsburg/helm-bibtex#48]
I'm trying helm-bibtex for the first time and am very impressed. I have my PDF files in several directories, including one for papers and one for books.  I'd therefore like helm-bibtex-library-path to support a list of directories, in the same way that helm-bibtex-bibliography supports a list of bib-files.

I suppose some people might also want the option to search all subdirectories of a given path, though that wouldn't meet my present need.

**Comment by tmalsburg** [comment]
Hi Nick, glad to hear that you like helm-bibtex.

I'm a little reluctant to add features whose main purpose it is to suit people's tastes; simply because there are so many different tastes and we will never be able to accommodate all of them.  I would simply copy all PDFs in one directory.  However, you are right when you point out that helm-bibtex already allows multiple bib files and having a dedicated library path for each of these bib files actually makes sense.  

@thisirs implemented [multiple library paths](https://github.com/thisirs/helm-bibtex/commit/66befb94c4b5c8c26dfb102f00ea26a3afc83b38) but hasn't submitted a pull request.  Could you have a look at his code and see if it does what you want?

**Comment by tmalsburg** [comment]
I added the feature in 52e2dd1658ee5c8dcf7030e711c3035cceae300c. Let me know if you experience any problems.

**Comment by higham** [comment]
Thank you - the multiple library paths feature works perfectly (as did what was in the pull request when I tried it).

**Comment by tmalsburg** [comment]
Great, thanks for the feedback.
