### ISSUE TITLE
Feature request: make fallback options helm actions

### ISSUE THREAD

**Issue by aksarkar** [tmalsburg/helm-bibtex#50]
The current implementation adds the fallbacks as another helm source and therefore requires navigating in the helm buffer to select a fallback. If these were actions instead, a user could hit tab and use helm filtering again to more quickly get to the fallback they wanted.

**Comment by tmalsburg** [comment]
If no entry matches your query, you can’t select actions, but that’s precisely the situation for which fallback options were introduced.  You can try it using the variant of `helm-bibtex` below which has no fallback options.  Enter some string that doesn’t match any publication and try to access the actions menu.

    (defun helm-bibtex1 ()
      "Search BibTeX entries."
      (interactive)
      (helm :sources '(helm-source-bibtex)
            :full-frame t
            :candidate-number-limit 500))

**Comment by aksarkar** [comment]
Yes, however I can select actions for a query with no matches in e.g. helm-find-files. I am not yet familiar enough with helm internals to know what's different in that implementation.

**Comment by tmalsburg** [comment]
It works in some helm sources but not in others.  For example in helm-for-files it doesn't work.  Helm-find-file apparently displays a dummy entry when nothing else matches.  But when we select the action "insert citation" on the dummy entry, what should happen then?  Should this produce an error?  I'm not really in favor of the dummy approach because it forces us to display actions for the dummy entry that we know are going to fail.

I see that it can be inconvenient to navigate to the fallback options but perhaps there is a better way to address that.  Perhaps there is a keyboard shortcut that allows the user to directly jump to the next source?  I wouldn't be surprised if Helm already had something like that.

**Comment by aksarkar** [comment]
helm-next-source is bound to C-o by default.

For helm-find-files, the actions themselves do all sorts of things on the dummy entry: fail silently, fail with an error message, or fail gracefully. So this probably isn't really a good idea, and the simplest thing for me to do would be to remove fallbacks I don't need.

**Comment by tmalsburg** [comment]
> helm-next-source is bound to C-o by default.

I didn't know this, thanks!

>  remove fallbacks I don't need.

Yes, that sounds like a good idea.  Fallback options can be configured using the customization variable `helm-bibtex-fallback-options`.
