### ISSUE TITLE
multiple options for find-pdf?

### ISSUE THREAD

**Issue by mclearc** [tmalsburg/helm-bibtex#63]
I title all my pdfs as `citekey short-title.pdf` or `citekey title.pdf`, whichever is shorter. Is there a way to set the `find-pdf` option so that helm-bibtex would first check the `short-title` of the bibtex entry and then move to `title` if the `short-title` entry is empty? Or am I better off just using the `file` entry, which includes the attachment file path and name? (Sorry, elisp noob here)

**Comment by tmalsburg** [comment]
You have to write your custom version of the function `helm-bibtex-find-pdf`.  If your bibtex file already has entries for the `file` field, the easiest solution would be to use that and I have the vague sense that someone may already have implemented that.  Otherwise I would go the `citekey + (short-)title` route.  You can probably use parts of this untested code snippet:

``` elisp
(let* ((entry (helm-bibtex-get-entry key))
       (title (helm-bibtex-get-value ("title" entry)))
       (pdf-name (s-concat key " " title ".pdf"))
       (pdf-path (f-join helm-bibtex-library-path pdf-name)))
  (when (f-exists? pdf-path)
	  pdf-path))
```
Note that this does not check for `short-title` (I didn't know that this field exists) and it assumes that `helm-bibtex-library-path` is a string instead a list of strings.  See the documentation of `helm-bibtex-library-path`.

**Comment by mclearc** [comment]
Thanks! I think you may have been thinking of the code in issue #53. I tried versions of some of the code there but couldn't get anything to work. I'll take a look at your suggested snippet above.

**Comment by tmalsburg** [comment]
Try starting with a simple dummy version of the function that just returns a hard-coded path and add features in small steps.

**Comment by mclearc** [comment]
Thanks. When I get a working example I'll update the thread here accordingly.
