### ISSUE TITLE
Feature Request: Allow user input during citation creation

### ISSUE THREAD

**Issue by etergo** [tmalsburg/helm-bibtex#68]
I would like to be able to enter a citation with user prompts for certain fields, in a similar manner to reftex. In the case of reftex any empty square bracket pairs are taken as user prompts. Thus, in the case of a \cite[]{} command, once I find the reference it then prompts me to fill in a value for [] and enters the completed citation into my buffer. I end up with, for example, \cite[234]{JREGB} or in the case of a \footcite[][]{} command I am prompted twice (once for the comment field, once for the page number), and can end up with \footcite[text][234]{JREGB} without having to manually go and fill in the information other than cite key.

I have searched the mailing list and played with helm-bibtex-format-citation-functions, but cannot find such a feature. I'm not sure what demand there is for it, but it would be fantastic if there was a way to do this.

**Comment by tmalsburg** [comment]
This feature does not exists at this time, at least not in helm-bibtex.  However, it sounds like something that org-ref might offer.  If you want to implement it yourself, you have to modify `helm-bibtex-format-citation-cite`.  Should be relatively easy.

By the way, which mailing list are you referring to?

**Comment by etergo** [comment]
Ok thanks for that. I'll have a look at modding the function. If the mod works do you want a pull request?

Regarding the mailing list that was an infelicitous way of putting it. I meant the lists.gnu.org archive, there were somewhat relevant posts in both the reftex and org-mode lists.

**Comment by etergo** [comment]
I have modified helm-bibtex-format-citation-cite using some of the code in the corresponding reftex function and now have the behaviour I describe above. Am happy to do a pull request if wanted.

**Comment by tmalsburg** [comment]
I'm not sure whether I want to include this feature at this point.  It's not my preferred way of inserting citations and eventually I'd like to include something that allows users to customize this without doing any Elisp programming.  But if you post the code here, I could include it in the customization section of the documentation.  Thank you.

**Comment by tmalsburg** [comment]
Thinking a little more about this, perhaps I do like this feature.  Below is my solution.  What do you think?

``` elisp
(defun helm-bibtex-format-citation-cite (keys)
  "Formatter for LaTeX citation macro."
  (let ((cite-command (read-from-minibuffer "Cite command: " "parencite" nil nil nil "parencite"))
        (prenote      (read-from-minibuffer "Prenote: "))
        (postnote     (read-from-minibuffer "Postnote: ")))
    (if (and (string= "" prenote) (string= "" postnote))
        (format "\\%s{%s}" cite-command (s-join ", " keys))
      (format "\\%s[%s][%s]{%s}" cite-command prenote postnote (s-join ", " keys)))))
```
We should probably have a dedicated minibuffer history for cite commands but I haven't yet figured out how to do this.

**Comment by etergo** [comment]
That works well. For your interest the code from reftex takes the cite command and only offers completion if the user has placed an empty pair of square brackets in it. That way the user is only prompted for completions if they want to be (could have the citation format as a defcustom). The weakness is that there is some work to add the options for multiple commands (e.g. I use both \cite and \footcite in my latex docs). The code is:

```elisp
 (defun helm-bibtex-format-citation-cite (keys)
  "Formatter for LaTeX citation macro."
  (setq string (format "\\footcite[][]{%s}" (s-join ", " keys)))
  (let ((start 0) (nth 0) value)
    (while (setq start (string-match "\\[\\]" string start))
      (setq value (save-match-data
                    (read-string (format "Optional argument %d: "
                                         (setq nth (1+ nth))))))
      (setq string (replace-match (concat "[" value "]") t t string))
      (setq start (1+ start))))
  string)
```

**Comment by tmalsburg** [comment]
According to the [biblatex documentation](http://ctan.mirrorcatalogs.com/macros/latex/contrib/biblatex/doc/biblatex.pdf) all cite commands take pre- and postnote arguments, the only exceptions are `nocite` and `supercite`.  So, I guess it would be enough to have special cases for when the user requests `nocite` and `supercite` but prompt for the notes otherwise.  If you don't need notes you simple hit enter two times, easy.

**Comment by etergo** [comment]
Sounds good. Thanks for your time implementing it. I'll close the issue.

**Comment by tmalsburg** [comment]
Well, let's keep the issue open until I committed something to the repository.

**Comment by tmalsburg** [comment]
Ok, added the feature in d9e4b2fcc49912351cac2b3c2d8a2d8d41af2f98.  Documentation in 2a810502c0028fd7fbe559b896a326df128e3d80.

**Comment by jagrg** [comment]
This is nice. I would suggest adding completion and possibly an `INITIAL-INPUT` for the sake of speed:

```emacs-lisp
(defun helm-bibtex-format-citation-cite (keys)
  "Formatter for LaTeX citation commands.  Prompts for the command and
for arguments if the commands can take any."
  (let ((cite-command (format "%s" (completing-read "Cite command: " helm-bibtex-cite-commands nil nil helm-bibtex-default-citation 'helm-bibtex-citation-command-history nil nil))))
    (if (member cite-command '("nocite" "supercite"))  ; These don't want arguments.
        (format "\\%s{%s}" cite-command (s-join ", " keys))
      (let ((prenote      (read-from-minibuffer "Prenote: "))
            (postnote     (read-from-minibuffer "Postnote: ")))
        (if (and (string= "" prenote) (string= "" postnote))
            (format "\\%s{%s}" cite-command (s-join ", " keys))
          (format "\\%s[%s][%s]{%s}" cite-command prenote postnote (s-join ", " keys)))))))

(setq helm-bibtex-default-citation "cite") ;; set to nil by default
```

It would be nice if we could also bypass the pre/postnote prompts. Maybe using different key strokes. For example, `C-m` to insert the citation directly and `C-n` to add the arguments accordingly when needed. I think this would make things a lot faster.

**Comment by tmalsburg** [comment]
Thanks for your feedback.  I considered an initial input but initial inputs are deprecated because they are considered [intrusive UI](https://www.gnu.org/software/emacs/manual/html_node/elisp/Initial-Input.html#Initial-Input) and I tend to agree with that view.  Also, what initial input is suitable depends strongly on the research field.  In my field, it's typically `parencite` but in others it's `cite`.  I think this is really handled by the minibuffer history.  The first time, I enter `parencite` and the next time I simply press `<up>` to access that citation command.

Completion is of course useful and I'll look into `completing-read`.

At first, I hesitated a little bit to include the prompts for pre and postnotes, but after using this interface for a few days I really think it's not a problem.  First, I use pre- and postnotes often enough that it's useful.  Second, when I don't need the notes, all I have to do is to press `RET RET RET` instead of just `RET` after selecting the citation command.  This costs me 500ms on average, which seems acceptable to me.  The cognitive load of having to decide which citation action to use would probably slow me down by an equal amount.  However, for users who use notes rarely or never (perhaps the citation style doesn't even allow them), we could add a customization variable for switching these prompts off completely.

**Comment by tmalsburg** [comment]
Added auto-completion in c06d07d7f0707d4fcab7b96d16a928e6ff74825a.  I also added a configurable default cite command, which does something similar as the initial input. A customization variable for switching off prompts is introduced in c81eb8909e5c5e31193af193690e0a9a461edc4f.

**Comment by jagrg** [comment]
The problem of `helm-bibtex-cite-prompt-for-notes` is that it's too restrictive. It's either RET RET RET or no prompts at all. I'm not sure if this is the best approach.

I also found the word choice for `helm-bibtex-cite-prompt-for-notes` misleading. The term notes is referenced in the context of annotation, so that might cause some confusion. I would use something like `helm-bibtex-cite-optional-arguments` instead, which seems more or less consistent with the `RefTeX` wording, and possibly `LaTeX` as well.

I understand the implications of the initial input being intrusive, but from a practical perspective it seems a lot easier. With the `cite` string on the minibuffer, I could simply add a `p`, `t` etc. and move on from there. In any case the initial input could be set to nil by default.

Could I also suggest adding this variable: https://github.com/jagrg/helm-bibtex/commit/93827a1db32d0fd23a335a34095b256cea62cda7

Thanks!

**Comment by tmalsburg** [comment]
If you disable prompts because you rarely use them, you can still add the pre- and postnote by hand.  After all, Emacs is also a text editor ;-) It's also possible to set the variable that controls prompts on a per-buffer basis for documents that use pre- and postnotes more often.

I agree about the naming of the variable controlling the prompts, it's not ideal.  I'll change it and hope that I don't make users unhappy who already set it.

I see your point regarding initial input.  But for the sake of UI consistency, I'd like to stick to the current solution, at least as the default behavior.  (I also have the impression that people are more and more gravitating to biblatex and there the most common citation commands don't start with `cite`.)  What I have currently is the following (not yet pushed): `helm-bibtex-cite-default-command` defines the default command and `helm-bibtex-cite-default-as-initial-input` defines how the default command is used.  It is either automatically inserted into the minibuffer (initial input) or used as the default in case that the user doesn't enter anything. 

I like `helm-bibtex-full-frame`, do you want to make a PR or shall I add it?

**Comment by tmalsburg** [comment]
`04d494a0950cbaf76614ec3ceb31778ff66eca8404d494a0950cbaf76614ec3ceb31778ff66eca84

**Comment by tmalsburg** [comment]
`helm-bibtex-cite-default-as-initial-input` added in 04d494a0950cbaf76614ec3ceb31778ff66eca84.

**Comment by jagrg** [comment]
I've also heard good things about biblatex and probably will make the switch myself eventually. Anyhow, thanks for making the changes. I'll give the PR a try.

**Comment by jagrg** [comment]
I was thinking that it may be a good idea to let the user to choose the number of prompts. Let me know what you think. 

```emacs-lisp
(defcustom helm-bibtex-number-of-optional-arguments 1
  "The number of optional arguments used for LaTeX citation.
Choose between 0 and 2."
  :group 'helm-bibtex
  :type 'number)

(defun helm-bibtex-format-citation-cite (keys)
  "Formatter for LaTeX citation commands.  Prompts for the command and
for arguments if the commands can take any."
  (let* ((initial (and helm-bibtex-cite-default-as-initial-input helm-bibtex-cite-default-command))
         (default (and (not helm-bibtex-cite-default-as-initial-input) helm-bibtex-cite-default-command))
         (default-info (if default (format " (default \"%s\")" default) ""))
         (cite-command (completing-read
                        (format "Cite command%s: " default-info)
                        helm-bibtex-cite-commands nil nil initial
                        'helm-bibtex-cite-command-history default nil)))
    (if (member cite-command '("nocite" "supercite"))  ; These don't want arguments.
        (format "\\%s{%s}" cite-command (s-join ", " keys))
      ;; no arg
      (if (= helm-bibtex-number-of-optional-arguments 0)
          (format "\\%s{%s}" cite-command (s-join ", " keys))
        ;; 1 arg
        (let ((pos (if (= helm-bibtex-number-of-optional-arguments 1) (read-from-minibuffer "Postnote[1]: ") "")))
          (if (string= "" pos)
              (format "\\%s{%s}" cite-command (s-join ", " keys))
            (format "\\%s[%s]{%s}" cite-command pos (s-join ", " keys)))
          ;; 2 arg...
          )))))
```

**Comment by tmalsburg** [comment]
Although this is more flexible than what we have now, I realize that it is still not flexible enough.  For example, some citation packages require optional arguments in pointy instead of square brackets.  Eventually, I think, helm-bibtex will need to have precise knowledge about citation packages and citation commands.  Unfortunately, this is a larger effort and I don't have time to implement it.  I think the current solution works really well with biblatex and I strongly recommend that people switch to biblatex because it is very clean and flexible and makes older packages pretty much obsolete.  Check it out, it even has natbib compatibility commands such that you don't have to rewrite your existing LaTeX documents.

**Comment by jagrg** [comment]
Just for the sake of reference, here's a working example of what I was thinking. With one argument I can still insert the prenote while in the minibuffer, which seems reasonable if I don't use prenotes often enough. 

```emacs-lisp
(defun helm-bibtex-format-citation-cite (keys)
  "Formatter for LaTeX citation commands.  Prompts for the command and
for arguments if the commands can take any."
  (let* ((initial (and helm-bibtex-cite-default-as-initial-input helm-bibtex-cite-default-command))
         (default (and (not helm-bibtex-cite-default-as-initial-input) helm-bibtex-cite-default-command))
         (default-info (if default (format " (default \"%s\")" default) ""))
         (cite-command (completing-read
                        (format "Cite command%s: " default-info)
                        helm-bibtex-cite-commands nil nil initial
                        'helm-bibtex-cite-command-history default nil)))
    (if (member cite-command '("nocite" "supercite"))  ; These don't want arguments.
        (format "\\%s{%s}" cite-command (s-join ", " keys))
      ;; 0 arg
      (if (= helm-bibtex-number-of-optional-arguments 0)
          (format "\\%s{%s}" cite-command (s-join ", " keys))
        ;; 1 arg
        (if (= helm-bibtex-number-of-optional-arguments 1)
            (let ((pos (if (= helm-bibtex-number-of-optional-arguments 1)
                           (read-from-minibuffer "Postnote[1]: ") "")))
              (if (and (= helm-bibtex-number-of-optional-arguments 1) (string= "" pos))
                  (format "\\%s{%s}" cite-command (s-join ", " keys))
                (format "\\%s[%s]{%s}"  cite-command pos (s-join ", " keys))))
          ;; 2 arg
          (let ((pre (if (= helm-bibtex-number-of-optional-arguments 2)
                         (read-from-minibuffer "Prenote[1]: ") ""))
                (pos (if (= helm-bibtex-number-of-optional-arguments 2)
                         (read-from-minibuffer "Postnote[2]: ") "")))
            (if (and (= helm-bibtex-number-of-optional-arguments 2) (string= "" pre) (string= "" pos))
                (format "\\%s{%s}" cite-command (s-join ", " keys))
              (format "\\%s[%s][%s]{%s}" cite-command pre pos (s-join ", " keys)))
            ))))))
```

**Comment by tmalsburg** [comment]
That's the beauty of Emacs.  If you don't like how something works, you simply change it.
