### ISSUE TITLE
multi-line candidates

### ISSUE THREAD

**Issue by jkitchin** [tmalsburg/helm-bibtex#89]
How feasible would it be to have multiline candidates? I would like to see the journal names and more authors in the helm candidates when searching. I think the best way to do that would be to make multiline entries. In helm you add (multiline) to the source to get that. Any thoughts?

**Comment by tmalsburg** [comment]
It is of course feasible but I imagine that it is quite a bit of work to write the formatting code.  After all, it would have to deal not just with articles but also with other entry types.

There is also the issue of performance.  Helm-bibtex stores stripped down versions of the entries in memory.  This is necessary for performance reasons.  If we store the complete entries, this consumes considerable amounts of memory (assuming a non-trivial bibliography) and slows down helm-bibtex quite a bit.  Fields like the journal field are currently not stored and we’d have to add it along with a bunch of other fields (e.g, booktitles for proceedings).

I see that it would be nice to have additional information displayed but I feel that the primary function of helm-bibtex (finding entries) would suffer from multi-line displays.  Specifically, I'm not sure if we would be making good use of screen real estate.  Using two lines for each entry would mean that we could fit only half as many entries on the screen.  I primarily use a Thinkpad X220 which has a 13'' screen.  On that screen, I could only display 20 instead of 40 entries and that would make finding the entry in question less efficient. The availability of journal information doesn’t outweight this loss in efficiency, because the journal rarely disambiguates between entries.  When I want to see which in journal an article was published, I simply select “Show entry” in the actions menu.

Finally, I assume that some subset of the users will prefer the current one-line display, which means that multi-line would have to be configurable.  Not impossible, but it raises the bar for an implementation and will also affect maintainability of the code and documentation.

**Comment by jkitchin** [comment]
those are all good points!

**Comment by tmalsburg** [comment]
> Using two lines for each entry would mean that we could fit only half as many entries on the screen.

Actually, we could only display a third of the entries because helm separates multi-line entries with a separator line if I recall correctly.

Having said all of the above, I think this is a useful discussion.

**Comment by jkitchin** [comment]
I decided to give this a try. You can see it here https://github.com/jkitchin/org-ref/blob/master/org-ref-helm-bibtex.el. You are right, it shows many fewer candidates, but on a larger monitor this is not to big a problem.

**Comment by tmalsburg** [comment]
Great.  Looking forward to see it in action.

**Comment by tmalsburg** [comment]
One suggestion. Perhaps you can name it something else than helm-bibtex?  Just to avoid confusion among users.  helm-bibliography is available to my knowledge.

**Comment by jkitchin** [comment]
that is a good idea. I renamed it to helm-cite, which is what i use it for ;)
